version: "3.8"

services:

  app:
    image: treasury-management
    container_name: treasury-app
    build:
      context: .
    ports:
      - "3000:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: treasury-db
    restart: always
    environment:
      POSTGRES_DB: treasury_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: